services:
  - type: web
    name: spotlight-backend
    env: go
    buildCommand: |
      go build -o main ./cmd/api
      psql $DATABASE_URL -f migrations/complete_schema.sql
    startCommand: ./main
    healthCheckPath: /health
    envVars:
      - key: GIN_MODE
        value: release
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080

databases:
  - name: spotlight-db
    databaseName: ajay_pd5y
    user: ajay_pd5y_user
    plan: free
    ipAllowList: [] 