services:
  - type: web
    name: spotlight-backend
    env: go
    buildCommand: go build -o main ./cmd/api
    startCommand: ./main
    healthCheckPath: /health
    envVars:
      - key: GIN_MODE
        value: release

databases:
  - name: spotlight-db
    databaseName: ajay_pd5y
    user: ajay_pd5y_user
    plan: free
    ipAllowList: [] 